In [ ]:
# Bài tập trên lớp từ 14h20-14h35

# Cho ma trận =[
#    [1,2,3],
#    [4,5,6],
#    [7,8,9]
#]

# Lấy 4,5,6
# Lấy 2,5
# Lấy 3,4
# Lấy 9,6,3

In [9]:
import numpy as np
x =[[1,2,3],[4,5,6],[7,8,9]]
mang=np.array(x)

print(mang)
# Lấy 4,5,6
print(mang[1, :])
# Lấy 2,5
print(mang[0:2, 1])
# Lấy 3,4
print(mang[[0,1],[2,0]])
# Lấy 9,6,3
print(mang[:3,-1][::-1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[2 5]
[3 4]
[9 6 3]


In [15]:
import numpy as np
np.ones((3,3))
array=([[1.,1.,1.],[1.,1.,1.],[1.,1.,1.]])
np.ones(3)
np.ones((3,3))+np.arange(3)


array([0, 1, 2])

In [16]:
x=np.arange(3)
x

array([0, 1, 2])

In [23]:
x=np.arange(3)
x = x.reshape((3,1))
x

array([[0],
       [1],
       [2]])

In [27]:

y=np.arange(3)
x+ y

array([0, 2, 4])

In [10]:
x=[1,2,3,4,5,6,7,8,9,10]
so_chan = [num for num in x if num % 2 == 0]
print(so_chan)

[2, 4, 6, 8, 10]


In [34]:
data = np.random.uniform(0,10,(150,5))
data.shape
X = data[:, :4]
Y = data[:, 4]
X.shape,Y.shape
dataset_size=X.shape[0]
train_size=int(0.7*dataset_size)
train_size
X_train=X[:train_size]
X_test=X[train_size:]
X_train.shape,X_test.shape
split= X_train.shape[0]//10
split


10