In [3]:
import torch

x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y
y = 5*x**6+3*x**3+2*x**1+x+2*x+5*x**4+1

# Tính đạo hàm
y.backward()

# Lấy giá trị đạo hàm
dy_dx = x.grad

print(f"Đạo hàm của y tại x = {x.item()} là: {dy_dx.item()}")


Đạo hàm của y tại x = 2.0 là: 1161.0


In [8]:
#BTVN
#Tạo một tensor có giá trị ban đầu là 2.0
# định nghãi hàm số và tính gradient
# y = x**3 + 2*x**2 + 5+x + 1
# hãy tính dy/dx tại gái trị của x
# Dừng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng
# BTVN 2:
# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 -10) và y là số điểm được tính theo công thức y = 3x + 5 + noise
# với noise là một giá trị ngẫu nhiên nhỏ
# 1. Khởi tạo tham số w và b ngẫu nhiên với require_radient = True
# 2,3.Tính gradient, MSE
# 4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alphe = 0.01
# 5. Lập lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình


# PYTORCH with tensor
import torch
import numpy as np

torch.__version__

# Chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

x = torch.from_numpy(arr)
print(x)

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4, 5])


In [12]:
print (x.dtype)
print (x.type)
torch.LongTensor

arr2 = np.arange(0,12).reshape(4,3)
print (arr2)

torch.int64
<built-in method type of Tensor object at 0x0000023F7B731900>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
<built-in method type of Tensor object at 0x0000023F7CD5F7F0>


In [15]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)
arr [0] = 99
print(x)


tensor([0, 1, 2, 3, 4])
tensor([99,  1,  2,  3,  4])


In [ ]:
#Giải thích lý do tại sao ? cho 2 trường hợp trên 
#Khi thay đổi giá trị arr[0] = 99, giá trị trong tensor x cũng thay đổi (x[0] trở thành 99).
#Tensor x được tạo bằng torch.from_numpy(arr) chia sẻ bộ nhớ với array arr. Do đó, mọi thay đổi trong arr sẽ ảnh hưởng trực tiếp đến x, và ngược lại.
# BTVN 4: Bạn hãy giúp best nasus về nhà tạo tensor với :
# Empyty
# Zeros
# Ones
# Random
# reahape với view và view as
import torch

# Tạo tensor Empty (tensor rỗng, giá trị không được khởi tạo)
empty_tensor = torch.empty(3, 4)  # Tạo tensor 3x4, giá trị ngẫu nhiên (không khởi tạo)
print("Empty tensor:\n", empty_tensor)

# Tạo tensor Zeros (tất cả giá trị là 0)
zeros_tensor = torch.zeros(2, 3)  # Tạo tensor 2x3, tất cả giá trị là 0
print("\nZeros tensor:\n", zeros_tensor)

# Tạo tensor Ones (tất cả giá trị là 1)
ones_tensor = torch.ones(4, 2)  # Tạo tensor 4x2, tất cả giá trị là 1
print("\nOnes tensor:\n", ones_tensor)

# Tạo tensor Random (giá trị ngẫu nhiên từ phân phối đều [0, 1))
random_tensor = torch.rand(3, 3)  # Tạo tensor 3x3, giá trị ngẫu nhiên từ 0 đến 1
print("\nRandom tensor:\n", random_tensor)

# Reshape tensor bằng view
# Tạo tensor ban đầu kích thước 2x4
original_tensor = torch.tensor([[1, 2, 3, 4],
                               [5, 6, 7, 8]])
print("\nOriginal tensor (2x4):\n", original_tensor)

# Sử dụng view để reshape thành 4x2
reshaped_view = original_tensor.view(4, 2)
print("\nReshaped tensor using view (4x2):\n", reshaped_view)

# Sử dụng view để reshape thành 1x8
reshaped_view_flat = original_tensor.view(1, 8)
print("\nReshaped tensor using view (1x8):\n", reshaped_view_flat)

# Sử dụng view_as để reshape (tương tự view, nhưng dựa trên tensor khác)
target_shape = torch.tensor([[0, 0], [0, 0], [0, 0], [0, 0]])  # Tensor 4x2
reshaped_view_as = original_tensor.view_as(target_shape)
print("\nReshaped tensor using view_as (4x2):\n", reshaped_view_as)

Empty tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Random tensor:
 tensor([[0.5923, 0.9337, 0.4427],
        [0.1079, 0.6479, 0.2008],
        [0.3692, 0.9363, 0.0525]])

Original tensor (2x4):
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Reshaped tensor using view (4x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Reshaped tensor using view (1x8):
 tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

Reshaped tensor using view_as (4x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
